"""The same SSH options the transport uses, written where `ssh` will find them.

Every operation Ops runs already reaches a Host correctly: strict checking, the
key trusted under the Host's *name* rather than its address, and the profile's
own known_hosts. A human reaching the same Host by hand had to reproduce that
from memory — four flags, one of which (`HostKeyAlias`) nobody types unprompted
because nothing on the command line hints that it is load-bearing.

So the safe way to connect was the long way, and the short way was
`-o StrictHostKeyChecking=accept-new`, which records an unverified key in the
operator's own `~/.ssh/known_hosts` under whatever address happened to be on
the command line — untracked, unreviewed, and in the one file this profile
deliberately stopped using. That happened on 2026-09-17, in exactly the
direction the design predicted. A control that is harder to follow than to
bypass is worth an operator's discipline and nothing more.

This renders the options as an `ssh_config` block so `ssh <host-id>` is both
the shortest and the correct path. It is generated rather than hand-copied
because a hand copy is a fifth place the alias and the known_hosts path have to
agree, and the one that drifts silently: the transport would keep refusing a
wrong key while the hand-typed block quietly trusted it.

The fragment is machine-local — it names this workstation's own private key and
an absolute path into the gitignored profile directory, so it is written beside
them rather than tracked. Generating it is the reviewed part.
"""

from __future__ import annotations

import os
import tempfile
from pathlib import Path

from eidolon_ops.config import HostConfig
from eidolon_ops.errors import OperationsError

#: The file the fragment is written to, inside the profile's own directory —
#: the same directory that holds the known_hosts it points at, so the two move
#: together and a profile pointed at a different board takes its `ssh` alias
#: with it.
FILENAME = "ssh_config"


def path_for(host: HostConfig) -> Path:
    """Where this profile's fragment belongs: beside its own known_hosts.

    Derived rather than configured. The fragment is a restatement of fields
    this profile already has, and a profile that could put it somewhere else
    would be a profile whose `ssh` alias and whose transport could be made to
    disagree about which Host they mean.
    """

    return host.known_hosts_file.parent / FILENAME


def render(host: HostConfig, *, alias: str, generated_by: str) -> str:
    """The `Host` block, carrying the options the transport uses and no others.

    ``StrictHostKeyChecking yes`` and ``HostKeyAlias`` are the point. The rest
    is what makes the alias worth typing: without them the short command is
    still shorter than the safe one and the operator still types the safe one
    wrong.
    """

    if not alias or any(character.isspace() for character in alias):
        raise OperationsError(f"{alias!r} is not usable as an ssh alias")
    known_hosts = host.known_hosts_file
    if not known_hosts.is_absolute():
        # A relative UserKnownHostsFile resolves against whatever directory the
        # operator happens to be in, which is the one thing a fragment included
        # from ~/.ssh/config can never assume.
        raise OperationsError(
            f"host.known_hosts_file must resolve to an absolute path to appear in an "
            f"ssh_config fragment: {known_hosts}"
        )
    lines = [
        f"# Generated by `{generated_by}`. Edits are overwritten; change the profile instead.",
        "#",
        "# These are the options every Ops operation already uses. They are here so that",
        "# reaching this Host by hand is the same act, and the shortest one: `ssh "
        f"{alias}`.",
        "#",
        "# Include it from ~/.ssh/config, above any `Host *` block — ssh keeps the first",
        "# value it is given for each option:",
        f"#     Include {path_for(host)}",
        "",
        f"Host {alias}",
        f"    HostName {host.hostname}",
        f"    User {host.user}",
        f"    Port {host.port}",
        f"    IdentityFile {host.identity_file}",
        # Otherwise an agent offers every key it holds before this one, and a
        # board that accepts some other key accepts the connection as somebody
        # else — which is a different question answered by accident.
        "    IdentitiesOnly yes",
        f"    UserKnownHostsFile {known_hosts}",
        # The whole reason a changed link is not a trust decision: trust is
        # granted under the Host's name, and HostName may be an address.
        f"    HostKeyAlias {host.hostname}",
        "    StrictHostKeyChecking yes",
        f"    ConnectTimeout {host.connect_timeout_seconds}",
    ]
    return "\n".join(lines) + "\n"


def write(path: Path, text: str) -> None:
    """Place the fragment, atomically and privately.

    Mode 0600 and a whole-file replace for the same reason the known_hosts
    beside it gets both: a half-written fragment is an `ssh` that silently
    stops applying `StrictHostKeyChecking`, and ssh itself refuses a config
    file others can write.
    """

    path.parent.mkdir(parents=True, exist_ok=True)
    handle, temporary = tempfile.mkstemp(dir=path.parent, prefix=f".{FILENAME}-")
    try:
        with os.fdopen(handle, "w", encoding="utf-8") as stream:
            stream.write(text)
        os.chmod(temporary, 0o600)
        os.replace(temporary, path)
    except BaseException:
        Path(temporary).unlink(missing_ok=True)
        raise
